version: '3'
services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      # HR効いてほしそうなやつ
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
      - ./frontend/index.html:/frontend/index.html
    command: npm run dev

  backend:
    build: backend
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/root/workdir
    init: true
    command: [ "make" ]
