#!/bin/bash
set -ue

## clang-format
target=`git diff --staged --name-only | grep -E ".+\.(c|h)"` || :

if [ -z $target ]; then
  echo -e "\033[35mno target file\033[m"
  exit 0
fi

echo -e "\033[34mclang-format target:" $target "\033[m"

# TODO: imageがないときbuildする
image=de-clang-format
has_image=`docker images -q $image`
if [ -z $has_image ]; then
  docker build -t $image -f hooks/Dockerfile_clang-format .
fi


docker run \
  --rm \
  -v "$(pwd):/workdir" \
  -w /workdir \
  --user "$(id -u):$(id -g)" \
  $image \
  -i $target

git add $target

echo -e "\033[32mpre-commit format is finished\033[m"