#!/bin/bash

## clang-format
# ターゲットになるc,hファイルは/backend内にあることを期待している
host_path=`git diff --staged --name-only | grep -E ".+\.(c|h)"`
target=`echo $host_path | sed -e "s/backend\///g"`

if [ -z $target ]; then
  exit 0
fi

echo "clang-format target:" $target

docker run \
  --rm \
  -v "$(pwd)/backend:/workdir" \
  -w /workdir \
  --user "$(id -u):$(id -g)" \
  de_backend \
  clang-format -i $target

git add $host_path

echo "pre-commit format is finished"