#!/bin/bash
set -ue

## clang-format
# ターゲットになるc,hファイルは/backend内にあることを期待している
host_path=`git diff --staged --name-only | grep -E ".+\.(c|h)"` || :
target=`echo $host_path | sed -e "s/backend\///g"`

if [ -z $target ]; then
  echo -e "\033[35mno target file\033[m"
  exit 0
fi

echo -e "\033[34mclang-format target:" $target "\033[m"

docker run \
  --rm \
  -v "$(pwd)/backend:/workdir" \
  -w /workdir \
  --user "$(id -u):$(id -g)" \
  de_backend \
  clang-format -i $target

git add $host_path

echo -e "\033[32mpre-commit format is finished\033[m"